---
name: pr

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches:
      - trunk
      - release-*
      - release/*
      - feature-*
  workflow_dispatch:
    inputs:
      profile_option:
        description: 'Which Rust build profile to use? (Default is lint)'
        required: false
        type: choice
        options:
          - 'lint'
          - 'release'
          - 'release-lto'
        default: 'lint'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'trunk' && github.sha || 'any-sha' }}
  cancel-in-progress: true

env:
  IGNORED_PATHS: '(^./docs/|^README.md$|^version.txt$|^acknowledgements.md$)'
  RUST_PROFILE: ${{ github.event.inputs.profile_option || 'lint' }}

jobs:

  build:
    name: Build Go & Rust
    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_BUCKET: ${{ secrets.SCCACHE_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: 'linux'

      - uses: mozilla-actions/sccache-action@v0.0.3

      - name: Set up make
        uses: ./.github/actions/setup-make

      - name: Set up cc
        uses: ./.github/actions/setup-cc

      - run: make build-runtime

      - name: Show sccache stats
        run: sccache --show-stats
